version: '3.2'
services:
  db:
    image: mongo:3.4

  test:
    build:
      context: .
      dockerfile: Dockerfile.python-test
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./donna
        target: /app/donna
        read_only: true
      - type: bind
        source: ./tests
        target: /app/tests
        read_only: true
